#!/usr/bin/env python3
"""Verify Cangjie's declared Unicode 17 script-coverage frontier.

Usage: verify_coverage.py Scripts.txt [generated_test.zig]

The manifest is an auditable frontier rather than a claim inferred from the
classifier enum. Every modeled script must have exact assigned-scalar coverage
and an OpenType tag mapping before it may appear in the manifest.

This build-time developer verifier intentionally uses Python, matching the
other Unicode data generators and the Fontations coverage gate in this repo.
"""

import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MANIFEST = Path(__file__).with_name("coverage.json")
LINE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)\b")


ZIG_SCRIPT_NAME_OVERRIDES = {
    # Unicode renamed the English property value from Oriya to Odia, while
    # Scripts.txt deliberately retains the stable property-value alias.
    "Oriya": "odia",
}


def render_test(manifest, ranges, total_script_count):
    names = manifest["exactly_audited_scripts"]
    lines = [
        "// Generated by tools/unicode/script/verify_coverage.py.",
        'const std = @import("std");',
        'const script = @import("script");',
        "",
        "fn expectScriptRange(expected: script.Script, first: u32, last: u32) !void {",
        "    var value = first;",
        "    while (value <= last) : (value += 1) {",
        "        try std.testing.expectEqual(expected, script.forCodepoint(@intCast(value)));",
        "    }",
        "}",
        "",
        'test "pinned Unicode script ranges are classified exhaustively" {',
    ]
    for name in names:
        internal_name = zig_name(name)
        count = sum(last - first + 1 for first, last in ranges[name])
        lines.append(f"    // {name}: {count} assigned scalars.")
        for first, last in ranges[name]:
            lines.append(
                f"    try expectScriptRange(.{internal_name}, "
                f"0x{first:x}, 0x{last:x});"
            )
    lines.append("}")
    lines.extend(
        [
            "",
            'test "unassigned Unicode scalars remain unknown" {',
        ]
    )
    cursor = 0
    assigned_ranges = sorted(
        (first, last)
        for script_ranges in ranges.values()
        for first, last in script_ranges
    )
    for first, last in assigned_ranges:
        if first < cursor:
            raise ValueError("overlapping Unicode Script ranges")
        if cursor < first:
            lines.append(
                f"    try expectScriptRange(.unknown, 0x{cursor:x}, 0x{first - 1:x});"
            )
        cursor = last + 1
    if cursor < 0x110000:
        lines.append(
            f"    try expectScriptRange(.unknown, 0x{cursor:x}, 0x10ffff);"
        )
    lines.extend(
        [
            "}",
            "",
            'test "coverage frontier counts remain explicit" {',
            f"    try std.testing.expectEqual(@as(usize, {len(manifest['modeled_scripts'])}), {len(manifest['modeled_scripts'])});",
            f"    try std.testing.expectEqual(@as(usize, {total_script_count}), {total_script_count});",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def zig_name(script):
    return ZIG_SCRIPT_NAME_OVERRIDES.get(script, script.lower())


def main() -> int:
    if len(sys.argv) not in (2, 3):
        raise SystemExit("usage: verify_coverage.py Scripts.txt [generated_test.zig]")
    source_path = Path(sys.argv[1])
    source_bytes = source_path.read_bytes()
    source = source_bytes.decode("utf-8")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    exact = manifest["exactly_audited_scripts"]
    expected_header = f"# Scripts-{manifest['unicode_version']}.txt\n"
    if not source.startswith(expected_header):
        raise SystemExit(f"expected {expected_header.strip()}")
    if hashlib.sha256(source_bytes).hexdigest() != manifest["source_sha256"]:
        raise SystemExit("Scripts.txt SHA-256 does not match the pinned Unicode source")

    counts: dict[str, int] = {}
    ranges: dict[str, list[tuple[int, int]]] = {}
    scripts: set[str] = set()
    for line in source.splitlines():
        match = LINE.match(line)
        if match is None:
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2) or match.group(1), 16)
        script = match.group(3)
        scripts.add(script)
        counts[script] = counts.get(script, 0) + last - first + 1
        ranges.setdefault(script, []).append((first, last))

    # Rebuild the committed runtime table and compare bytes. This makes the
    # exhaustive classifier test prove both semantic coverage and that the
    # generated artifact is reproducible from the pinned source.
    with tempfile.TemporaryDirectory() as directory:
        generated = Path(directory) / "data.bin"
        subprocess.run(
            [
                sys.executable,
                str(Path(__file__).with_name("generate_data.py")),
                str(source_path),
                str(generated),
            ],
            check=True,
        )
        committed = ROOT / "src/unicode/script/data.bin"
        if generated.read_bytes() != committed.read_bytes():
            raise SystemExit("generated Unicode Script data.bin is stale")

    modeled = manifest["modeled_scripts"]
    if len(modeled) != len(set(modeled)):
        raise SystemExit("duplicate modeled script in coverage manifest")
    unknown = sorted(set(modeled) - scripts)
    if unknown:
        raise SystemExit(f"manifest names unknown Unicode scripts: {unknown}")

    root = (ROOT / "src/unicode/script/types.zig").read_text(encoding="utf-8")
    facade = (ROOT / "src/unicode.zig").read_text(encoding="utf-8")
    missing_artifacts = []
    if len(exact) != len(set(exact)):
        raise SystemExit("duplicate exactly audited script in coverage manifest")
    if set(exact) != set(modeled):
        missing = sorted(set(modeled) - set(exact))
        extra = sorted(set(exact) - set(modeled))
        raise SystemExit(
            "exact audit list must match modeled coverage; "
            f"missing={missing}, extra={extra}"
        )
    expected_counts = manifest["expected_assigned_scalar_counts"]
    if set(expected_counts) != set(exact):
        missing = sorted(set(exact) - set(expected_counts))
        extra = sorted(set(expected_counts) - set(exact))
        raise SystemExit(
            "assigned-scalar counts must match exact audit list; "
            f"missing={missing}, extra={extra}"
        )

    for script in exact:
        internal_name = zig_name(script)
        if f"    {internal_name}," not in root:
            missing_artifacts.append(f"{script}: Script enum")
        if (
            script not in ("Common", "Inherited")
            and f".{internal_name} =>" not in facade
        ):
            missing_artifacts.append(f"{script}: OpenType mapping")
        expected = manifest["expected_assigned_scalar_counts"][script]
        if counts.get(script) != expected:
            missing_artifacts.append(
                f"{script}: expected {expected} assigned scalars, got {counts.get(script)}"
            )
    if missing_artifacts:
        raise SystemExit("script coverage verification failed:\n  - " + "\n  - ".join(missing_artifacts))

    if len(sys.argv) == 3:
        Path(sys.argv[2]).write_text(
            render_test(manifest, ranges, len(scripts)), encoding="utf-8"
        )

    covered = set(modeled)
    print(
        f"Unicode {manifest['unicode_version']} script coverage: "
        f"{len(covered)}/{len(scripts)} scripts modeled; "
        f"{len(scripts - covered)} remain explicit gaps"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
