// Generated by tools/generate_canonical_decomposition.py from UnicodeData.txt.
// Only recursive canonical decompositions whose first component is a
// Unicode mark are stored; these are the sequences USE does not recompose.
const Record = struct {
    codepoint: u21,
    offset: u16,
    len: u8,
};

const records = [_]Record{
    .{ .codepoint = 0x344, .offset = 0, .len = 2 },
    .{ .codepoint = 0x9cb, .offset = 2, .len = 2 },
    .{ .codepoint = 0x9cc, .offset = 4, .len = 2 },
    .{ .codepoint = 0xb48, .offset = 6, .len = 2 },
    .{ .codepoint = 0xb4b, .offset = 8, .len = 2 },
    .{ .codepoint = 0xb4c, .offset = 10, .len = 2 },
    .{ .codepoint = 0xbca, .offset = 12, .len = 2 },
    .{ .codepoint = 0xbcb, .offset = 14, .len = 2 },
    .{ .codepoint = 0xbcc, .offset = 16, .len = 2 },
    .{ .codepoint = 0xc48, .offset = 18, .len = 2 },
    .{ .codepoint = 0xcc0, .offset = 20, .len = 2 },
    .{ .codepoint = 0xcc7, .offset = 22, .len = 2 },
    .{ .codepoint = 0xcc8, .offset = 24, .len = 2 },
    .{ .codepoint = 0xcca, .offset = 26, .len = 2 },
    .{ .codepoint = 0xccb, .offset = 28, .len = 3 },
    .{ .codepoint = 0xd4a, .offset = 31, .len = 2 },
    .{ .codepoint = 0xd4b, .offset = 33, .len = 2 },
    .{ .codepoint = 0xd4c, .offset = 35, .len = 2 },
    .{ .codepoint = 0xdda, .offset = 37, .len = 2 },
    .{ .codepoint = 0xddc, .offset = 39, .len = 2 },
    .{ .codepoint = 0xddd, .offset = 41, .len = 3 },
    .{ .codepoint = 0xdde, .offset = 44, .len = 2 },
    .{ .codepoint = 0xf73, .offset = 46, .len = 2 },
    .{ .codepoint = 0xf75, .offset = 48, .len = 2 },
    .{ .codepoint = 0xf76, .offset = 50, .len = 2 },
    .{ .codepoint = 0xf78, .offset = 52, .len = 2 },
    .{ .codepoint = 0xf81, .offset = 54, .len = 2 },
    .{ .codepoint = 0xf93, .offset = 56, .len = 2 },
    .{ .codepoint = 0xf9d, .offset = 58, .len = 2 },
    .{ .codepoint = 0xfa2, .offset = 60, .len = 2 },
    .{ .codepoint = 0xfa7, .offset = 62, .len = 2 },
    .{ .codepoint = 0xfac, .offset = 64, .len = 2 },
    .{ .codepoint = 0xfb9, .offset = 66, .len = 2 },
    .{ .codepoint = 0x1b3b, .offset = 68, .len = 2 },
    .{ .codepoint = 0x1b3d, .offset = 70, .len = 2 },
    .{ .codepoint = 0x1b40, .offset = 72, .len = 2 },
    .{ .codepoint = 0x1b41, .offset = 74, .len = 2 },
    .{ .codepoint = 0x1b43, .offset = 76, .len = 2 },
    .{ .codepoint = 0x1112e, .offset = 78, .len = 2 },
    .{ .codepoint = 0x1112f, .offset = 80, .len = 2 },
    .{ .codepoint = 0x1134b, .offset = 82, .len = 2 },
    .{ .codepoint = 0x1134c, .offset = 84, .len = 2 },
    .{ .codepoint = 0x113c5, .offset = 86, .len = 2 },
    .{ .codepoint = 0x113c7, .offset = 88, .len = 2 },
    .{ .codepoint = 0x113c8, .offset = 90, .len = 2 },
    .{ .codepoint = 0x114bb, .offset = 92, .len = 2 },
    .{ .codepoint = 0x114bc, .offset = 94, .len = 2 },
    .{ .codepoint = 0x114be, .offset = 96, .len = 2 },
    .{ .codepoint = 0x115ba, .offset = 98, .len = 2 },
    .{ .codepoint = 0x115bb, .offset = 100, .len = 2 },
    .{ .codepoint = 0x11938, .offset = 102, .len = 2 },
    .{ .codepoint = 0x16121, .offset = 104, .len = 2 },
    .{ .codepoint = 0x16122, .offset = 106, .len = 2 },
    .{ .codepoint = 0x16123, .offset = 108, .len = 2 },
    .{ .codepoint = 0x16124, .offset = 110, .len = 2 },
    .{ .codepoint = 0x16125, .offset = 112, .len = 2 },
    .{ .codepoint = 0x16126, .offset = 114, .len = 3 },
    .{ .codepoint = 0x16127, .offset = 117, .len = 3 },
    .{ .codepoint = 0x16128, .offset = 120, .len = 3 },
};

const components = [_]u21{
    0x308,   0x301,   0x9c7,   0x9be,   0x9c7,   0x9d7,   0xb47,   0xb56,   0xb47,   0xb3e,   0xb47,   0xb57,   0xbc6,   0xbbe,   0xbc7,   0xbbe,
    0xbc6,   0xbd7,   0xc46,   0xc56,   0xcbf,   0xcd5,   0xcc6,   0xcd5,   0xcc6,   0xcd6,   0xcc6,   0xcc2,   0xcc6,   0xcc2,   0xcd5,   0xd46,
    0xd3e,   0xd47,   0xd3e,   0xd46,   0xd57,   0xdd9,   0xdca,   0xdd9,   0xdcf,   0xdd9,   0xdcf,   0xdca,   0xdd9,   0xddf,   0xf71,   0xf72,
    0xf71,   0xf74,   0xfb2,   0xf80,   0xfb3,   0xf80,   0xf71,   0xf80,   0xf92,   0xfb7,   0xf9c,   0xfb7,   0xfa1,   0xfb7,   0xfa6,   0xfb7,
    0xfab,   0xfb7,   0xf90,   0xfb5,   0x1b3a,  0x1b35,  0x1b3c,  0x1b35,  0x1b3e,  0x1b35,  0x1b3f,  0x1b35,  0x1b42,  0x1b35,  0x11131, 0x11127,
    0x11132, 0x11127, 0x11347, 0x1133e, 0x11347, 0x11357, 0x113c2, 0x113c2, 0x113c2, 0x113b8, 0x113c2, 0x113c9, 0x114b9, 0x114ba, 0x114b9, 0x114b0,
    0x114b9, 0x114bd, 0x115b8, 0x115af, 0x115b9, 0x115af, 0x11935, 0x11930, 0x1611e, 0x1611e, 0x1611e, 0x16129, 0x1611e, 0x1611f, 0x16129, 0x1611f,
    0x1611e, 0x16120, 0x1611e, 0x1611e, 0x1611f, 0x1611e, 0x16129, 0x1611f, 0x1611e, 0x1611e, 0x16120,
};

pub fn forCodepoint(codepoint: u21) ?[]const u21 {
    var low: usize = 0;
    var high: usize = records.len;
    while (low < high) {
        const mid = low + (high - low) / 2;
        const record = records[mid];
        if (codepoint < record.codepoint) {
            high = mid;
        } else if (codepoint > record.codepoint) {
            low = mid + 1;
        } else {
            return components[record.offset .. record.offset + record.len];
        }
    }
    return null;
}

test "canonical decomposition recursively expands Sinhala split matras" {
    const testing = @import("std").testing;
    try testing.expectEqualSlices(u21, &.{ 0x0dd9, 0x0dca }, forCodepoint(0x0dda).?);
    try testing.expectEqualSlices(u21, &.{ 0x0dd9, 0x0dcf, 0x0dca }, forCodepoint(0x0ddd).?);
    try testing.expect(forCodepoint('A') == null);
}
