#!/usr/bin/env python3
"""Generate the Unicode 17 UAX #50 Vertical_Orientation table.

Usage:
    tools/unicode/vertical/generate_data.py \
        path/to/VerticalOrientation.txt src/unicode/vertical_data.zig

The UCD default is Rotated. Emitting only U/Tu/Tr ranges keeps lookup compact
while still covering every Unicode code point through that explicit default.
"""

from __future__ import annotations

import hashlib
import pathlib
import sys
from collections import Counter


EXPECTED_HEADER = "# VerticalOrientation-17.0.0.txt\n"
EXPECTED_SOURCE_RANGES = 2470
MAX_CODEPOINT = 0x10FFFF


def parse(path: pathlib.Path) -> tuple[list[tuple[int, int, str]], bytes]:
    raw = path.read_bytes()
    text = raw.decode("utf-8")
    if not text.startswith(EXPECTED_HEADER):
        raise SystemExit("expected Unicode 17.0 VerticalOrientation data")

    ranges: list[tuple[int, int, str]] = []
    previous_end = -1
    for line_number, line in enumerate(text.splitlines(), 1):
        payload = line.split("#", 1)[0].strip()
        if not payload:
            continue
        fields = [field.strip() for field in payload.split(";")]
        if len(fields) != 2 or fields[1] not in {"R", "U", "Tu", "Tr"}:
            raise SystemExit(f"invalid record at line {line_number}")
        bounds = fields[0].split("..")
        start = int(bounds[0], 16)
        end = int(bounds[-1], 16)
        if start > end or end > MAX_CODEPOINT or start <= previous_end:
            raise SystemExit(f"unordered or overlapping record at line {line_number}")
        ranges.append((start, end, fields[1]))
        previous_end = end

    if len(ranges) != EXPECTED_SOURCE_RANGES:
        raise SystemExit(
            f"expected {EXPECTED_SOURCE_RANGES} source ranges, found {len(ranges)}"
        )
    return ranges, raw


def merge_non_rotated(
    ranges: list[tuple[int, int, str]],
) -> list[tuple[int, int, str]]:
    result: list[tuple[int, int, str]] = []
    for start, end, value in ranges:
        if value == "R":
            continue
        if result and result[-1][2] == value and result[-1][1] + 1 == start:
            result[-1] = (result[-1][0], end, value)
        else:
            result.append((start, end, value))
    return result


def classification_counts(
    ranges: list[tuple[int, int, str]],
) -> Counter[str]:
    counts: Counter[str] = Counter({"R": MAX_CODEPOINT + 1})
    for start, end, value in ranges:
        count = end - start + 1
        if value != "R":
            counts["R"] -= count
            counts[value] += count
    return counts


def zig_value(value: str) -> str:
    return {
        "U": "upright",
        "Tu": "transformed_upright",
        "Tr": "transformed_rotated",
    }[value]


def generate(
    source: pathlib.Path,
    output: pathlib.Path,
) -> None:
    ranges, raw = parse(source)
    compact = merge_non_rotated(ranges)
    counts = classification_counts(ranges)
    digest = hashlib.sha256(raw).hexdigest()

    lines = [
        "// Generated by tools/unicode/vertical/generate_data.py from Unicode 17.0.0.",
        f"// Source SHA-256: {digest}",
        "",
        "pub const Range = struct {",
        "    start: u21,",
        "    end: u21,",
        "    value: Value,",
        "};",
        "",
        "pub const Value = enum(u2) {",
        "    upright,",
        "    transformed_upright,",
        "    transformed_rotated,",
        "};",
        "",
        f"pub const source_range_count: usize = {len(ranges)};",
        f"pub const explicit_range_count: usize = {len(compact)};",
        f"pub const rotated_count: usize = {counts['R']};",
        f"pub const upright_count: usize = {counts['U']};",
        f"pub const transformed_upright_count: usize = {counts['Tu']};",
        f"pub const transformed_rotated_count: usize = {counts['Tr']};",
        "",
        "pub const ranges = [_]Range{",
    ]
    for start, end, value in compact:
        lines.append(
            "    .{ "
            f".start = 0x{start:x}, .end = 0x{end:x}, "
            f".value = .{zig_value(value)} "
            "},"
        )
    lines.extend(["};", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str]) -> None:
    if len(argv) != 3:
        raise SystemExit(
            "usage: generate_data.py VerticalOrientation.txt output.zig"
        )
    generate(pathlib.Path(argv[1]), pathlib.Path(argv[2]))


if __name__ == "__main__":
    main(sys.argv)
