// Generated by tools/generate_vowel_constraints.py from USE data dated 2019-11-08, 23:22:00 GMT [AG].
// Match lengths are 0 (none), 2, or 3 Unicode scalars.
const Constraint = struct {
    first: u21,
    second: u21,
    third: u21 = 0,
};

const constraints = [_]Constraint{
    .{ .first = 0x905, .second = 0x93a },
    .{ .first = 0x905, .second = 0x93b },
    .{ .first = 0x905, .second = 0x93e },
    .{ .first = 0x905, .second = 0x945 },
    .{ .first = 0x905, .second = 0x946 },
    .{ .first = 0x905, .second = 0x949 },
    .{ .first = 0x905, .second = 0x94a },
    .{ .first = 0x905, .second = 0x94b },
    .{ .first = 0x905, .second = 0x94c },
    .{ .first = 0x905, .second = 0x94f },
    .{ .first = 0x905, .second = 0x956 },
    .{ .first = 0x905, .second = 0x957 },
    .{ .first = 0x906, .second = 0x93a },
    .{ .first = 0x906, .second = 0x945 },
    .{ .first = 0x906, .second = 0x946 },
    .{ .first = 0x906, .second = 0x947 },
    .{ .first = 0x906, .second = 0x948 },
    .{ .first = 0x909, .second = 0x941 },
    .{ .first = 0x90f, .second = 0x945 },
    .{ .first = 0x90f, .second = 0x946 },
    .{ .first = 0x90f, .second = 0x947 },
    .{ .first = 0x930, .second = 0x94d, .third = 0x907 },
    .{ .first = 0x985, .second = 0x9be },
    .{ .first = 0x98b, .second = 0x9c3 },
    .{ .first = 0x98c, .second = 0x9e2 },
    .{ .first = 0xa05, .second = 0xa3e },
    .{ .first = 0xa05, .second = 0xa48 },
    .{ .first = 0xa05, .second = 0xa4c },
    .{ .first = 0xa72, .second = 0xa3f },
    .{ .first = 0xa72, .second = 0xa40 },
    .{ .first = 0xa72, .second = 0xa47 },
    .{ .first = 0xa73, .second = 0xa41 },
    .{ .first = 0xa73, .second = 0xa42 },
    .{ .first = 0xa73, .second = 0xa4b },
    .{ .first = 0xa85, .second = 0xabe },
    .{ .first = 0xa85, .second = 0xabe, .third = 0xac5 },
    .{ .first = 0xa85, .second = 0xabe, .third = 0xac8 },
    .{ .first = 0xa85, .second = 0xac5 },
    .{ .first = 0xa85, .second = 0xac7 },
    .{ .first = 0xa85, .second = 0xac8 },
    .{ .first = 0xa85, .second = 0xac9 },
    .{ .first = 0xa85, .second = 0xacb },
    .{ .first = 0xa85, .second = 0xacc },
    .{ .first = 0xac5, .second = 0xabe },
    .{ .first = 0xb05, .second = 0xb3e },
    .{ .first = 0xb0f, .second = 0xb57 },
    .{ .first = 0xb13, .second = 0xb57 },
    .{ .first = 0xb85, .second = 0xbc2 },
    .{ .first = 0xc12, .second = 0xc4c },
    .{ .first = 0xc12, .second = 0xc55 },
    .{ .first = 0xc3f, .second = 0xc55 },
    .{ .first = 0xc46, .second = 0xc55 },
    .{ .first = 0xc4a, .second = 0xc55 },
    .{ .first = 0xc89, .second = 0xcbe },
    .{ .first = 0xc8b, .second = 0xcbe },
    .{ .first = 0xc92, .second = 0xccc },
    .{ .first = 0xd07, .second = 0xd57 },
    .{ .first = 0xd09, .second = 0xd57 },
    .{ .first = 0xd0e, .second = 0xd46 },
    .{ .first = 0xd12, .second = 0xd3e },
    .{ .first = 0xd12, .second = 0xd57 },
    .{ .first = 0xd85, .second = 0xdcf },
    .{ .first = 0xd85, .second = 0xdd0 },
    .{ .first = 0xd85, .second = 0xdd1 },
    .{ .first = 0xd8b, .second = 0xddf },
    .{ .first = 0xd8d, .second = 0xdd8 },
    .{ .first = 0xd8f, .second = 0xddf },
    .{ .first = 0xd91, .second = 0xdca },
    .{ .first = 0xd91, .second = 0xdd9 },
    .{ .first = 0xd91, .second = 0xdda },
    .{ .first = 0xd91, .second = 0xddc },
    .{ .first = 0xd91, .second = 0xddd },
    .{ .first = 0xd91, .second = 0xdde },
    .{ .first = 0xd94, .second = 0xddf },
    .{ .first = 0x11005, .second = 0x11038 },
    .{ .first = 0x1100b, .second = 0x1103e },
    .{ .first = 0x1100f, .second = 0x11042 },
    .{ .first = 0x11200, .second = 0x1122c },
    .{ .first = 0x11200, .second = 0x1122c, .third = 0x11231 },
    .{ .first = 0x11200, .second = 0x11231 },
    .{ .first = 0x11200, .second = 0x11233 },
    .{ .first = 0x11206, .second = 0x1122c },
    .{ .first = 0x1122c, .second = 0x11230 },
    .{ .first = 0x1122c, .second = 0x11231 },
    .{ .first = 0x11240, .second = 0x1122e },
    .{ .first = 0x112b0, .second = 0x112e0 },
    .{ .first = 0x112b0, .second = 0x112e5 },
    .{ .first = 0x112b0, .second = 0x112e6 },
    .{ .first = 0x112b0, .second = 0x112e7 },
    .{ .first = 0x112b0, .second = 0x112e8 },
    .{ .first = 0x11481, .second = 0x114b0 },
    .{ .first = 0x1148b, .second = 0x114ba },
    .{ .first = 0x1148d, .second = 0x114ba },
    .{ .first = 0x114aa, .second = 0x114b5 },
    .{ .first = 0x114aa, .second = 0x114b6 },
    .{ .first = 0x11600, .second = 0x11639 },
    .{ .first = 0x11600, .second = 0x1163a },
    .{ .first = 0x11601, .second = 0x11639 },
    .{ .first = 0x11601, .second = 0x1163a },
    .{ .first = 0x11680, .second = 0x116ad },
    .{ .first = 0x11680, .second = 0x116b4 },
    .{ .first = 0x11680, .second = 0x116b5 },
    .{ .first = 0x11686, .second = 0x116b2 },
};

fn canStartConstraint(codepoint: u21) bool {
    return switch (codepoint) {
        0x905, 0x906, 0x909, 0x90f, 0x930, 0x985, 0x98b, 0x98c => true,
        0xa05, 0xa72, 0xa73, 0xa85, 0xac5, 0xb05, 0xb0f, 0xb13 => true,
        0xb85, 0xc12, 0xc3f, 0xc46, 0xc4a, 0xc89, 0xc8b, 0xc92 => true,
        0xd07, 0xd09, 0xd0e, 0xd12, 0xd85, 0xd8b, 0xd8d, 0xd8f => true,
        0xd91, 0xd94, 0x11005, 0x1100b, 0x1100f, 0x11200, 0x11206, 0x1122c => true,
        0x11240, 0x112b0, 0x11481, 0x1148b, 0x1148d, 0x114aa, 0x11600, 0x11601 => true,
        0x11680, 0x11686 => true,
        else => false,
    };
}

pub fn matchLength(codepoints: []const u21, start: usize) u2 {
    if (start >= codepoints.len or codepoints.len - start < 2) return 0;
    const first = codepoints[start];
    // Most shaping scalars cannot begin one of the 103 invalid
    // sequences. Reject them through the exact 50-scalar set
    // before entering the lower-bound search over duplicate keys.
    if (!canStartConstraint(first)) return 0;
    var low: usize = 0;
    var high: usize = constraints.len;
    while (low < high) {
        const mid = low + (high - low) / 2;
        if (constraints[mid].first < first) low = mid + 1 else high = mid;
    }
    var index = low;
    while (index < constraints.len and constraints[index].first == first) : (index += 1) {
        const constraint = constraints[index];
        if (constraint.second != codepoints[start + 1]) continue;
        if (constraint.third == 0) return 2;
        if (codepoints.len - start >= 3 and constraint.third == codepoints[start + 2]) return 3;
    }
    return 0;
}

test "vowel constraints match two and three scalar sequences" {
    const testing = @import("std").testing;
    try testing.expectEqual(@as(u2, 2), matchLength(&.{ 0x0905, 0x093a }, 0));
    try testing.expectEqual(@as(u2, 3), matchLength(&.{ 0x0930, 0x094d, 0x0907 }, 0));
    try testing.expectEqual(@as(u2, 0), matchLength(&.{ 0x0905, 0x093f }, 0));
    try testing.expect(canStartConstraint(0x0905));
    try testing.expect(!canStartConstraint(0x0915));
}
