#!/usr/bin/env python3
"""Translate HarfBuzz's Unicode USE category table into compact Zig data.

Usage:
    tools/generate_use_categories.py \
        path/to/hb-ot-shaper-use-table.hh \
        src/use/category_data.zig

HarfBuzz generates this packed table from the Unicode Indic syllabic and
positional properties plus Microsoft USE overrides. Reusing the generated
Unicode artifact keeps Cangjie's state machine on the same category vocabulary
without copying HarfBuzz's C expression into the shaping hot path by hand.

This translator is deliberately pinned to the Unicode 17 default-size packing
layout. It fails if the upstream generator changes its packing topology, so an
update cannot silently produce corrupt category data.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


ARRAY_RE = re.compile(
    r"static const (uint8_t|uint16_t) (hb_use_u8|hb_use_u16)\[(\d+)\]\s*=\s*"
    r"\{(.*?)\};",
    re.DOTALL,
)
VERSION_RE = re.compile(r"# IndicSyllabicCategory-([0-9.]+)\.txt")
EXPECTED_LENGTHS = {"hb_use_u8": 3343, "hb_use_u16": 864}
TABLE_LIMIT = 921_600
CATEGORY_VALUES = {
    "O": 0,
    "B": 1,
    "N": 4,
    "GB": 5,
    "CGJ": 6,
    "SUB": 11,
    "H": 12,
    "HN": 13,
    "ZWNJ": 14,
    "WJ": 16,
    "R": 18,
    "VPre": 22,
    "VMPre": 23,
    "FAbv": 24,
    "FBlw": 25,
    "FPst": 26,
    "MAbv": 27,
    "MBlw": 28,
    "MPst": 29,
    "MPre": 30,
    "CMAbv": 31,
    "CMBlw": 32,
    "VAbv": 33,
    "VBlw": 34,
    "VPst": 35,
    "VMAbv": 37,
    "VMBlw": 38,
    "VMPst": 39,
    "SMAbv": 41,
    "CS": 43,
    "IS": 44,
    "FMAbv": 45,
    "FMBlw": 46,
    "FMPst": 47,
    "Sk": 48,
    "G": 49,
    "J": 50,
    "SB": 51,
    "SE": 52,
    "HVM": 53,
    "HM": 54,
    "HR": 55,
    "RK": 56,
}


def parse_header(path: Path) -> tuple[str, dict[str, list[int]]]:
    text = path.read_text(encoding="utf-8")
    default_arm = text.split("#ifndef HB_OPTIMIZE_SIZE", 1)[1].split("#else", 1)[0]
    version_match = VERSION_RE.search(text)
    if version_match is None:
        raise ValueError("missing IndicSyllabicCategory Unicode version")

    arrays: dict[str, list[int]] = {}
    for storage_type, name, declared_length, body in ARRAY_RE.findall(default_arm):
        values: list[int] = []
        for token in re.findall(r"\d+|[A-Za-z][A-Za-z0-9]*", body):
            if token[0].isdigit():
                values.append(int(token))
            elif token in CATEGORY_VALUES:
                values.append(CATEGORY_VALUES[token])
            else:
                raise ValueError(f"{name}: unknown generated category token {token!r}")
        length = int(declared_length)
        if len(values) != length:
            raise ValueError(f"{name}: declared {length} values but parsed {len(values)}")
        maximum = 0xFF if storage_type == "uint8_t" else 0xFFFF
        if any(value > maximum for value in values):
            raise ValueError(f"{name}: value exceeds {storage_type}")
        arrays[name] = values

    for name, expected_length in EXPECTED_LENGTHS.items():
        actual = len(arrays.get(name, ()))
        if actual != expected_length:
            raise ValueError(
                f"unsupported HarfBuzz USE packing: {name} has {actual} values, "
                f"expected {expected_length}"
            )
    return version_match.group(1), arrays


def render_array(name: str, type_name: str, values: list[int]) -> list[str]:
    lines = [f"const {name} = [_]{type_name}{{"]
    width = 24 if type_name == "u8" else 16
    for start in range(0, len(values), width):
        chunk = ", ".join(str(value) for value in values[start : start + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return lines


def render(version: str, arrays: dict[str, list[int]]) -> str:
    lines = [
        f"// Generated by tools/generate_use_categories.py from HarfBuzz Unicode {version}.",
        "// The packed topology mirrors hb-ot-shaper-use-table.hh's default-size arm.",
        "",
    ]
    lines.extend(render_array("u8_data", "u8", arrays["hb_use_u8"]))
    lines.append("")
    lines.extend(render_array("u16_data", "u16", arrays["hb_use_u16"]))
    lines.extend(
        [
            "",
            "fn nibble(index: usize) u8 {",
            "    return (u8_data[index >> 1] >> @intCast((index & 1) << 2)) & 15;",
            "}",
            "",
            "pub fn forCodepoint(codepoint: u21) u8 {",
            f"    if (codepoint >= {TABLE_LIMIT}) return 0;",
            "    const u: usize = codepoint;",
            "    const half = u >> 1;",
            "    const level_1_group = (half >> 3) >> 3;",
            "    const level_1 = u8_data[113 + @as(usize, nibble(level_1_group >> 5)) * 32 + (level_1_group & 31)];",
            "    const level_2 = u16_data[@as(usize, level_1) * 8 + ((half >> 3) & 7)];",
            # packTab's u16 layer already stores byte offsets into the next
            # level; unlike the surrounding u8 layers it is not a page index.
            "    const level_3 = u8_data[625 + @as(usize, level_2) + (half & 7)];",
            "    return u8_data[2953 + @as(usize, level_3) * 2 + (u & 1)];",
            "}",
            "",
            'test "Unicode 17 USE categories cover Indic-v3 and modern scripts" {',
            '    const testing = @import("std").testing;',
            "    try testing.expectEqual(@as(u8, 1), forCodepoint(0x0905));",
            "    try testing.expectEqual(@as(u8, 35), forCodepoint(0x093e));",
            "    try testing.expectEqual(@as(u8, 1), forCodepoint(0x112b0));",
            "    try testing.expectEqual(@as(u8, 35), forCodepoint(0x112e0));",
            "    try testing.expectEqual(@as(u8, 0), forCodepoint(0x0020));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    version, arrays = parse_header(Path(sys.argv[1]))
    Path(sys.argv[2]).write_text(render(version, arrays), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
