#!/usr/bin/env python3
"""Generate a compact Zig trie for USE/Indic invalid vowel sequences.

Usage:
    tools/generate_vowel_constraints.py \
        path/to/ms-use/IndicShapingInvalidCluster.txt \
        src/use/vowel_constraints.zig

The source file is maintained by the Microsoft USE specification and consumed
by HarfBuzz. The generated trie is script-independent because every prohibited
sequence begins with a script-specific codepoint; layout only invokes it for
shapers whose upstream preprocess hook uses these constraints.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


VERSION_RE = re.compile(r"^# Date:\s*(.+)$")


def parse(path: Path) -> tuple[str, list[tuple[int, ...]]]:
    date = "unknown"
    sequences: list[tuple[int, ...]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        date_match = VERSION_RE.match(raw)
        if date_match:
            date = date_match.group(1)
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints = tuple(int(token, 16) for token in line.split(";", 1)[0].split())
        if len(codepoints) < 2 or len(codepoints) > 3:
            raise ValueError(f"unsupported invalid-vowel sequence: {codepoints!r}")
        sequences.append(codepoints)
    if not sequences:
        raise ValueError("no invalid vowel constraints found")
    return date, sorted(set(sequences))


def render(date: str, sequences: list[tuple[int, ...]]) -> str:
    first_codepoints = sorted({sequence[0] for sequence in sequences})
    lines = [
        f"// Generated by tools/generate_vowel_constraints.py from USE data dated {date}.",
        "// Match lengths are 0 (none), 2, or 3 Unicode scalars.",
        "const Constraint = struct {",
        "    first: u21,",
        "    second: u21,",
        "    third: u21 = 0,",
        "};",
        "",
        "const constraints = [_]Constraint{",
    ]
    for sequence in sequences:
        third = f", .third = 0x{sequence[2]:x}" if len(sequence) == 3 else ""
        lines.append(
            f"    .{{ .first = 0x{sequence[0]:x}, .second = 0x{sequence[1]:x}{third} }},"
        )
    lines.extend(
        [
            "};",
            "",
            "fn canStartConstraint(codepoint: u21) bool {",
            "    return switch (codepoint) {",
        ]
    )
    for start in range(0, len(first_codepoints), 8):
        chunk = ", ".join(
            f"0x{codepoint:x}" for codepoint in first_codepoints[start : start + 8]
        )
        lines.append(f"        {chunk} => true,")
    lines.extend(
        [
            "        else => false,",
            "    };",
            "}",
            "",
            "pub fn matchLength(codepoints: []const u21, start: usize) u2 {",
            "    if (start >= codepoints.len or codepoints.len - start < 2) return 0;",
            "    const first = codepoints[start];",
            f"    // Most shaping scalars cannot begin one of the {len(sequences)} invalid",
            f"    // sequences. Reject them through the exact {len(first_codepoints)}-scalar set",
            "    // before entering the lower-bound search over duplicate keys.",
            "    if (!canStartConstraint(first)) return 0;",
            "    var low: usize = 0;",
            "    var high: usize = constraints.len;",
            "    while (low < high) {",
            "        const mid = low + (high - low) / 2;",
            "        if (constraints[mid].first < first) low = mid + 1 else high = mid;",
            "    }",
            "    var index = low;",
            "    while (index < constraints.len and constraints[index].first == first) : (index += 1) {",
            "        const constraint = constraints[index];",
            "        if (constraint.second != codepoints[start + 1]) continue;",
            "        if (constraint.third == 0) return 2;",
            "        if (codepoints.len - start >= 3 and constraint.third == codepoints[start + 2]) return 3;",
            "    }",
            "    return 0;",
            "}",
            "",
            'test "vowel constraints match two and three scalar sequences" {',
            '    const testing = @import("std").testing;',
            "    try testing.expectEqual(@as(u2, 2), matchLength(&.{ 0x0905, 0x093a }, 0));",
            "    try testing.expectEqual(@as(u2, 3), matchLength(&.{ 0x0930, 0x094d, 0x0907 }, 0));",
            "    try testing.expectEqual(@as(u2, 0), matchLength(&.{ 0x0905, 0x093f }, 0));",
            "    try testing.expect(canStartConstraint(0x0905));",
            "    try testing.expect(!canStartConstraint(0x0915));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    date, sequences = parse(Path(sys.argv[1]))
    Path(sys.argv[2]).write_text(render(date, sequences), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
