#!/usr/bin/env python3
"""Generate USE-retained canonical Unicode decompositions for Zig shaping.

Usage:
    tools/generate_canonical_decomposition.py \
        path/to/UnicodeData.txt \
        src/unicode/canonical_decomposition.zig

Compatibility mappings are excluded. Recursive expansion produces canonical
NFD components, then retains only mappings whose first component is a Unicode
mark—the exact class that USE's compose hook refuses to recombine.
"""

from __future__ import annotations

import sys
from pathlib import Path


def parse(path: Path) -> tuple[dict[int, tuple[int, ...]], dict[int, str]]:
    direct: dict[int, tuple[int, ...]] = {}
    categories: dict[int, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        if len(fields) < 6:
            continue
        codepoint = int(fields[0], 16)
        categories[codepoint] = fields[2]
        mapping = fields[5]
        if not mapping or mapping.startswith("<"):
            continue
        direct[codepoint] = tuple(int(token, 16) for token in mapping.split())
    return direct, categories


def expand_all(
    direct: dict[int, tuple[int, ...]],
    categories: dict[int, str],
) -> dict[int, tuple[int, ...]]:
    memo: dict[int, tuple[int, ...]] = {}

    def expand(codepoint: int, stack: frozenset[int] = frozenset()) -> tuple[int, ...]:
        if codepoint in memo:
            return memo[codepoint]
        if codepoint in stack:
            raise ValueError(f"canonical decomposition cycle at U+{codepoint:04X}")
        result: list[int] = []
        for component in direct.get(codepoint, (codepoint,)):
            if component in direct:
                result.extend(expand(component, stack | {codepoint}))
            else:
                result.append(component)
        memo[codepoint] = tuple(result)
        return memo[codepoint]

    return {
        codepoint: expanded
        for codepoint in sorted(direct)
        if len(expanded := expand(codepoint)) > 1
        and categories.get(expanded[0], "").startswith("M")
    }


def render(entries: dict[int, tuple[int, ...]]) -> str:
    flat: list[int] = []
    records: list[tuple[int, int, int]] = []
    for codepoint, components in entries.items():
        records.append((codepoint, len(flat), len(components)))
        flat.extend(components)
    if any(length > 0xFF for _, _, length in records):
        raise ValueError("canonical decomposition length exceeds u8")

    lines = [
        "// Generated by tools/generate_canonical_decomposition.py from UnicodeData.txt.",
        "// Only recursive canonical decompositions whose first component is a",
        "// Unicode mark are stored; these are the sequences USE does not recompose.",
        "const Record = struct {",
        "    codepoint: u21,",
        "    offset: u16,",
        "    len: u8,",
        "};",
        "",
        "const records = [_]Record{",
    ]
    for codepoint, offset, length in records:
        lines.append(
            f"    .{{ .codepoint = 0x{codepoint:x}, .offset = {offset}, .len = {length} }},"
        )
    lines.extend(["};", "", "const components = [_]u21{"])
    for start in range(0, len(flat), 16):
        chunk = ", ".join(f"0x{value:x}" for value in flat[start : start + 16])
        lines.append(f"    {chunk},")
    lines.extend(
        [
            "};",
            "",
            "pub fn forCodepoint(codepoint: u21) ?[]const u21 {",
            "    var low: usize = 0;",
            "    var high: usize = records.len;",
            "    while (low < high) {",
            "        const mid = low + (high - low) / 2;",
            "        const record = records[mid];",
            "        if (codepoint < record.codepoint) {",
            "            high = mid;",
            "        } else if (codepoint > record.codepoint) {",
            "            low = mid + 1;",
            "        } else {",
            "            return components[record.offset .. record.offset + record.len];",
            "        }",
            "    }",
            "    return null;",
            "}",
            "",
            'test "canonical decomposition recursively expands Sinhala split matras" {',
            '    const testing = @import("std").testing;',
            "    try testing.expectEqualSlices(u21, &.{ 0x0dd9, 0x0dca }, forCodepoint(0x0dda).?);",
            "    try testing.expectEqualSlices(u21, &.{ 0x0dd9, 0x0dcf, 0x0dca }, forCodepoint(0x0ddd).?);",
            "    try testing.expect(forCodepoint('A') == null);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    direct, categories = parse(Path(sys.argv[1]))
    entries = expand_all(direct, categories)
    Path(sys.argv[2]).write_text(render(entries), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
