#!/usr/bin/env python3
"""Generate recursive canonical Unicode decompositions for Zig shaping.

Usage:
    tools/generate_canonical_decomposition.py \
        path/to/UnicodeData.txt \
        src/unicode/canonical_decomposition.zig

Compatibility mappings are excluded. Recursive expansion produces canonical
NFD components. Generic source normalization uses the complete table when a
font lacks a precomposed scalar; the generator also emits the mark-leading
split-matra subset that USE's compose hook refuses to recombine.
"""

from __future__ import annotations

import sys
from pathlib import Path


def parse(path: Path) -> tuple[dict[int, tuple[int, ...]], dict[int, str]]:
    direct: dict[int, tuple[int, ...]] = {}
    categories: dict[int, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        if len(fields) < 6:
            continue
        codepoint = int(fields[0], 16)
        categories[codepoint] = fields[2]
        mapping = fields[5]
        if not mapping or mapping.startswith("<"):
            continue
        direct[codepoint] = tuple(int(token, 16) for token in mapping.split())
    return direct, categories


def expand_all(
    direct: dict[int, tuple[int, ...]],
) -> dict[int, tuple[int, ...]]:
    memo: dict[int, tuple[int, ...]] = {}

    def expand(codepoint: int, stack: frozenset[int] = frozenset()) -> tuple[int, ...]:
        if codepoint in memo:
            return memo[codepoint]
        if codepoint in stack:
            raise ValueError(f"canonical decomposition cycle at U+{codepoint:04X}")
        result: list[int] = []
        for component in direct.get(codepoint, (codepoint,)):
            if component in direct:
                result.extend(expand(component, stack | {codepoint}))
            else:
                result.append(component)
        memo[codepoint] = tuple(result)
        return memo[codepoint]

    return {
        codepoint: expanded
        for codepoint in sorted(direct)
        if (expanded := expand(codepoint))
    }


def table_source(
    name: str,
    entries: dict[int, tuple[int, ...]],
) -> tuple[list[str], int]:
    flat: list[int] = []
    records: list[tuple[int, int, int]] = []
    for codepoint, components in entries.items():
        records.append((codepoint, len(flat), len(components)))
        flat.extend(components)
    if any(length > 0xFF for _, _, length in records):
        raise ValueError("canonical decomposition length exceeds u8")

    lines = [
        f"const {name}_records = [_]Record{{",
    ]
    for codepoint, offset, length in records:
        lines.append(
            f"    .{{ .codepoint = 0x{codepoint:x}, .offset = {offset}, .len = {length} }},"
        )
    lines.extend(["};", "", f"const {name}_components = [_]u21{{"])
    for start in range(0, len(flat), 16):
        chunk = ", ".join(f"0x{value:x}" for value in flat[start : start + 16])
        lines.append(f"    {chunk},")
    lines.extend(["};", ""])
    return lines, len(flat)


def render(
    direct_entries: dict[int, tuple[int, ...]],
    recursive_entries: dict[int, tuple[int, ...]],
    categories: dict[int, str],
) -> str:
    lines = [
        "// Generated by tools/generate_canonical_decomposition.py from Unicode 17.0.0.",
        "// Compatibility mappings are excluded; components are recursively expanded.",
        "const Record = struct {",
        "    codepoint: u21,",
        "    offset: u16,",
        "    len: u8,",
        "};",
        "",
    ]
    mark_leading_entries = {
        codepoint: components
        for codepoint, components in recursive_entries.items()
        if len(components) > 1 and
        categories.get(components[0], "").startswith("M")
    }
    direct_lines, _ = table_source("direct", direct_entries)
    recursive_lines, _ = table_source("recursive", recursive_entries)
    mark_leading_lines, _ = table_source("mark_leading", mark_leading_entries)
    lines.extend(direct_lines)
    lines.extend(recursive_lines)
    lines.extend(mark_leading_lines)
    lines.extend(
        [
            "fn lookup(codepoint: u21, records: []const Record, components: []const u21) ?[]const u21 {",
            "    var low: usize = 0;",
            "    var high: usize = records.len;",
            "    while (low < high) {",
            "        const mid = low + (high - low) / 2;",
            "        const record = records[mid];",
            "        if (codepoint < record.codepoint) {",
            "            high = mid;",
            "        } else if (codepoint > record.codepoint) {",
            "            low = mid + 1;",
            "        } else {",
            "            return components[record.offset .. record.offset + record.len];",
            "        }",
            "    }",
            "    return null;",
            "}",
            "",
            "pub fn directForCodepoint(codepoint: u21) ?[]const u21 {",
            "    return lookup(codepoint, &direct_records, &direct_components);",
            "}",
            "",
            "pub fn forCodepoint(codepoint: u21) ?[]const u21 {",
            "    return lookup(codepoint, &recursive_records, &recursive_components);",
            "}",
            "",
            "pub fn markLeadingForCodepoint(codepoint: u21) ?[]const u21 {",
            "    return lookup(codepoint, &mark_leading_records, &mark_leading_components);",
            "}",
            "",
            'test "canonical decomposition recursively expands Sinhala split matras" {',
            '    const testing = @import("std").testing;',
            "    try testing.expectEqualSlices(u21, &.{ 0x0dd9, 0x0dca }, markLeadingForCodepoint(0x0dda).?);",
            "    try testing.expectEqualSlices(u21, &.{ 0x0dd9, 0x0dcf, 0x0dca }, markLeadingForCodepoint(0x0ddd).?);",
            "    try testing.expectEqualSlices(u21, &.{ 0x0041, 0x0302, 0x0301 }, forCodepoint(0x1ea4).?);",
            "    try testing.expectEqualSlices(u21, &.{ 0x00c2, 0x0301 }, directForCodepoint(0x1ea4).?);",
            "    try testing.expectEqualSlices(u21, &.{ 0x00c5 }, directForCodepoint(0x212b).?);",
            "    try testing.expectEqualSlices(u21, &.{ 0x0041, 0x030a }, forCodepoint(0x212b).?);",
            "    try testing.expect(markLeadingForCodepoint(0x1ea4) == null);",
            "    try testing.expect(forCodepoint('A') == null);",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    source = Path(sys.argv[1])
    direct, categories = parse(source)
    # U+1CCFA is new in Unicode 17. Pinning this sentinel prevents silently
    # regenerating one shaping table from an older system UCD.
    if 0x1CCFA not in categories:
        raise SystemExit("expected Unicode 17.0 UnicodeData.txt")
    entries = expand_all(direct)
    Path(sys.argv[2]).write_text(render(direct, entries, categories), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
