#!/usr/bin/env python3
"""Generate the compact Zig General_Category=Mn range table.

Usage:
    tools/generate_nonspacing_marks.py \
        path/to/extracted/DerivedGeneralCategory.txt \
        src/unicode/mark/nonspacing.zig

HarfBuzz synthesizes OpenType mark classes from Unicode General_Category when
a font has no GDEF GlyphClassDef. Grapheme_Cluster_Break=Extend is not an
equivalent substitute: it also contains spacing modifier letters, variation
selectors, and other characters whose advances must remain intact.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


LINE_RE = re.compile(
    r"^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([A-Za-z]{2})\b"
)


def parse_ranges(path: Path) -> tuple[str, list[tuple[int, int]]]:
    version = "unknown"
    ranges: list[tuple[int, int]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# DerivedGeneralCategory-"):
            version = line.removeprefix("# DerivedGeneralCategory-").removesuffix(
                ".txt"
            )
        match = LINE_RE.match(line)
        if match is None or match.group(3) != "Mn":
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2) or match.group(1), 16)
        ranges.append((first, last))

    ranges.sort()
    merged: list[tuple[int, int]] = []
    for first, last in ranges:
        if first > last or last > 0x10FFFF:
            raise ValueError(f"invalid Mn range: {first:X}..{last:X}")
        if merged and first <= merged[-1][1]:
            raise ValueError(
                f"overlapping Mn ranges: {merged[-1][0]:X}..{merged[-1][1]:X} "
                f"and {first:X}..{last:X}"
            )
        if merged and first == merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], last)
        else:
            merged.append((first, last))
    return version, merged


def render(version: str, ranges: list[tuple[int, int]]) -> str:
    lines = [
        f"// Generated by tools/generate_nonspacing_marks.py from Unicode {version}.",
        "// Only General_Category=Nonspacing_Mark (Mn) ranges are stored.",
        "const Range = struct {",
        "    first: u21,",
        "    last: u21,",
        "};",
        "",
        "const ranges = [_]Range{",
    ]
    for first, last in ranges:
        lines.append(f"    .{{ .first = 0x{first:x}, .last = 0x{last:x} }},")
    lines.extend(
        [
            "};",
            "",
            "pub fn contains(codepoint: u21) bool {",
            "    var low: usize = 0;",
            "    var high: usize = ranges.len;",
            "    while (low < high) {",
            "        const mid = low + (high - low) / 2;",
            "        const range = ranges[mid];",
            "        if (codepoint < range.first) {",
            "            high = mid;",
            "        } else if (codepoint > range.last) {",
            "            low = mid + 1;",
            "        } else {",
            "            return true;",
            "        }",
            "    }",
            "    return false;",
            "}",
            "",
            'test "nonspacing marks distinguish Mn from grapheme extenders and Mc" {',
            '    const testing = @import("std").testing;',
            "    try testing.expect(contains(0x0301));",
            "    try testing.expect(contains(0x111c9));",
            "    try testing.expect(contains(0x1e6e3));",
            "    try testing.expect(!contains(0x111ce));",
            "    try testing.expect(!contains(0xff9e));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    version, ranges = parse_ranges(input_path)
    output_path.write_text(render(version, ranges), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
