#!/usr/bin/env python3
"""Generate the compact Zig Canonical_Combining_Class range table.

Usage:
    tools/generate_canonical_combining_class.py \
        path/to/extracted/DerivedCombiningClass.txt \
        src/unicode/canonical_combining_class.zig

The input is the Unicode Character Database's DerivedCombiningClass.txt. The
generator drops the default class zero, sorts the remaining property ranges,
and merges adjacent ranges that have the same class.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


LINE_RE = re.compile(
    r"^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*(\d+)\b"
)


def parse_ranges(path: Path) -> tuple[str, list[tuple[int, int, int]]]:
    version = "unknown"
    ranges: list[tuple[int, int, int]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# DerivedCombiningClass-"):
            version = line.removeprefix("# DerivedCombiningClass-").removesuffix(".txt")
        match = LINE_RE.match(line)
        if match is None:
            continue
        first = int(match.group(1), 16)
        last = int(match.group(2) or match.group(1), 16)
        combining_class = int(match.group(3))
        if combining_class != 0:
            ranges.append((first, last, combining_class))

    ranges.sort()
    merged: list[tuple[int, int, int]] = []
    for first, last, combining_class in ranges:
        if first > last or last > 0x10FFFF or combining_class > 0xFF:
            raise ValueError(f"invalid CCC range: {first:X}..{last:X}; {combining_class}")
        if merged and first <= merged[-1][1]:
            raise ValueError(
                f"overlapping CCC ranges: {merged[-1][0]:X}..{merged[-1][1]:X} "
                f"and {first:X}..{last:X}"
            )
        if (
            merged
            and first == merged[-1][1] + 1
            and combining_class == merged[-1][2]
        ):
            previous_first, _, previous_class = merged[-1]
            merged[-1] = (previous_first, last, previous_class)
        else:
            merged.append((first, last, combining_class))
    return version, merged


def render(version: str, ranges: list[tuple[int, int, int]]) -> str:
    lines = [
        f"// Generated by tools/generate_canonical_combining_class.py from Unicode {version}.",
        "// Only non-zero Canonical_Combining_Class ranges are stored; every",
        "// unlisted codepoint has CCC=Not_Reordered (0).",
        "const Range = struct {",
        "    first: u21,",
        "    last: u21,",
        "    class: u8,",
        "};",
        "",
        "const ranges = [_]Range{",
    ]
    for first, last, combining_class in ranges:
        lines.append(
            f"    .{{ .first = 0x{first:x}, .last = 0x{last:x}, "
            f".class = {combining_class} }},"
        )
    lines.extend(
        [
            "};",
            "",
            "pub fn forCodepoint(codepoint: u21) u8 {",
            "    var low: usize = 0;",
            "    var high: usize = ranges.len;",
            "    while (low < high) {",
            "        const mid = low + (high - low) / 2;",
            "        const range = ranges[mid];",
            "        if (codepoint < range.first) {",
            "            high = mid;",
            "        } else if (codepoint > range.last) {",
            "            low = mid + 1;",
            "        } else {",
            "            return range.class;",
            "        }",
            "    }",
            "    return 0;",
            "}",
            "",
            'test "canonical combining classes include Tai Tham marks" {',
            '    const testing = @import("std").testing;',
            "    try testing.expectEqual(@as(u8, 9), forCodepoint(0x1a60));",
            "    try testing.expectEqual(@as(u8, 230), forCodepoint(0x1a7a));",
            "    try testing.expectEqual(@as(u8, 0), forCodepoint(0x1a43));",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    version, ranges = parse_ranges(input_path)
    output_path.write_text(render(version, ranges), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
